PACKAGE_NAME="sur40"
PACKAGE_VERSION="2.0"
BUILT_MODULE_NAME[0]="sur40"
DEST_MODULE_LOCATION[0]="/updates"
MAKE[0]="make -C ${kernel_source_dir} M=${dkms_tree}/${PACKAGE_NAME}/${PACKAGE_VERSION}/build modules"
CLEAN="make -C ${kernel_source_dir} M=${dkms_tree}/${PACKAGE_NAME}/${PACKAGE_VERSION}/build clean"
AUTOINSTALL="yes"
